export const REQUEST_EVENTS_API_DATA = "REQUEST_EVENTS_API_DATA";
export const RECEIVE_EVENTS_API_DATA = "RESPONSE_EVENTS_API_DATA";
export const FAILED_RECEIVE_EVENTS_API_DATA = "FAILED_RECEIVE_EVENTS_API_DATA";